config/routes.rb
Rails.application.routes.draw do
  root 'users#index'


  resources :users do 
    resources :appointments
  end
  resources :doctors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord    
    has_many :appointments
    has_many :users, through: :appointments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
    has_many :appointments
    has_many :doctors, through: :appointments, dependent: :destroy

    def full_name
        "#{self.first_name} #{self.last_name}"
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_user
  before_action :set_doctor
  

  def index
    @patients = @user.appointments.where(role: 'pacient')
    @doctors = @user.appointments.where(role: 'doctor')
  end

  def show
  end

  def new
    @users = User.all - @user.doctors
    @appointment = @user.appointments.new
  end

  def create
    @appointment = @user.appointments.new(appointment_params)
    if @appointment.save
      redirect_to user_appointments_path(@user)
    else 
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @appointment = @user.appointments.find(params[:id])
    @appointment.destroy
    redirect_to user_appointments_path(@user)
  end

  private
  
  def set_user
    @user = User.find(params[:user_id])
  end

  def set_doctor
    @Doctor = Doctor.find(params[:user_id])
  end

  def appointment_params
    params.require(:appointment).permit(:role, :user_id)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
 
  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to doctors_path
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private
  
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<div class="container">
<h1><%= "#{@user.full_name}"%>'s Appointments:</h1>
<% @user.appointments.each do |appointment| %>
<h2><%= appointment.date%></h2>
<p>Dr. <%= appointment.doctor.last_name%><p>
 <%= link_to 'Delete Doctor', user_appointment_path(@user, appointment), method: :delete%>
<% end %>
<br>
<h2>Create Appointment</h2>
<%= link_to 'Add Appointment', new_user_appointment_path(@user) %>
</div>

app/views/appointments/new.html.erb
<div class="container">
<h1>Add an Appointment</h1>
<%= form_for [@user, @appointment] do |f|%>
  <%= f.label :user%>
  <%=f.select :user_id, @users.collect { |u| [u.first_name, u.id] }%>
  <br />
  <%= f.label :date %>
  <%= f.datetime_field :date%>
  <br />
  <%= f.submit%>
  <%end%>
  </div>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>

     <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, autofocus: true, placeholder: "First Name" %>

    <%= f.submit%>
<% end %>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<%= render partial: 'form' %>
<%= link_to 'Back', doctors_path%>

app/views/doctors/index.html.erb
<div class="container">
<h1>- Doctors -</h1>
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2> 
<% @doctors.each do |doctor| %>
    <h2>~ <%= link_to "Dr. #{doctor.last_name}", doctor_path(doctor)%><h2>
    <%= link_to 'Edit Doctor', edit_doctor_path(doctor)%>
    <%= link_to 'Delete Doctor', doctor, method: :delete%>
    <br>
    <br>
<% end %>

app/views/doctors/new.html.erb
<div class="container">
<h1>Create Doctor</h1>
<%= render partial: 'form' %>
<%= link_to 'Back', doctors_path%>
<div>

app/views/doctors/show.html.erb
<h1><%= "Dr. #{@doctor.last_name}, #{@doctor.first_name} "%></h1>
<%= link_to 'Show Appointments', user_appointments_path(@doctor)%>

app/views/layouts/_navbar.html.erb
<nav>
<ul>
    <li><%=link_to 'Users', users_path %></li>
    <li><%=link_to 'Doctors', doctors_path %></li>
    <li><%=link_to 'Create user', new_user_path %></li>
    <li><%=link_to 'Create Doctor', new_doctor_path %></li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>

     <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, autofocus: true, placeholder: "First Name" %>

    <%= f.submit%>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Users</h1>
<%= render partial: 'form'%>
<%= link_to 'Back', users_path%>

app/views/users/index.html.erb
<div class="container"> 
<h1>- Users -</h1>
<h2><%= @users.length <= 0 ? "No Users" : "" %></h2> 
<% @users.each do |user| %>
    <h2>~ <%= link_to user.full_name, user_path(user)%><h2>
    <%= link_to 'Edit User', edit_user_path(user)%>
    <%= link_to 'Delete User', user, method: :delete%>
    <br>
    <br>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container">
<h1>Create User</h1>
<%= render partial: 'form'%>
<%= link_to 'Back', users_path%>
</div>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<%= link_to 'Show Appointments', user_appointments_path(@user)%>